package diner_dash;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author luisdiegomontealegrebadilla
 */
public class Game_screen extends javax.swing.JFrame {

    /**
     * Creates new form Game_screen
     */
    public Game_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bck_menu_btn = new javax.swing.JButton();
        door = new javax.swing.JLabel();
        rest_backgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bck_menu_btn.setText("Salir");
        bck_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck_menu_btnActionPerformed(evt);
            }
        });
        getContentPane().add(bck_menu_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1067, 0, 70, -1));

        door.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door.png"))); // NOI18N
        getContentPane().add(door, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 330, 180));

        rest_backgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rest_floor.jpeg"))); // NOI18N
        getContentPane().add(rest_backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bck_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck_menu_btnActionPerformed
        WarningPanel warning = new WarningPanel();
        JOptionPane.showConfirmDialog(warning, "¿Desea regresar al menu principal?");
        if (JOptionPane.showConfirmDialog(warning,"¿Desea regresar al menu principal?")== JOptionPane.YES_OPTION){
            this.dispose();
            Main_menu menu = new Main_menu();
            menu.setLocationRelativeTo(null);
            menu.setTitle("Menu Principal");
            menu.setVisible(true);
        }else{
            //pending
        }
        
    }//GEN-LAST:event_bck_menu_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck_menu_btn;
    private javax.swing.JLabel door;
    private javax.swing.JLabel rest_backgrnd;
    // End of variables declaration//GEN-END:variables
}
