/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diner_dash;

/**
 *
 * @author luisdiegomontealegrebadilla
 */
public class Main_menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_menu
     */
    public Main_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        ext_btn = new javax.swing.JButton();
        play_btn = new javax.swing.JButton();
        about = new javax.swing.JButton();
        main_m_bckgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diner_dsh.png"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 480, 150));

        ext_btn.setText("Salir");
        ext_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ext_btnActionPerformed(evt);
            }
        });
        getContentPane().add(ext_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 180, 50));

        play_btn.setText("Jugar");
        play_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_btnActionPerformed(evt);
            }
        });
        getContentPane().add(play_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 180, 50));

        about.setText("Acerca del Juego");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 140, 40));

        main_m_bckgrnd.setIcon(new javax.swing.ImageIcon("/Users/luisdiegomontealegrebadilla/Ing. Software/Estructuras de datos y algoritmos/Proyecto/Diner_Dash/src/rest_bckgrnd.jpeg")); // NOI18N
        getContentPane().add(main_m_bckgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ext_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ext_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_ext_btnActionPerformed

    private void play_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_btnActionPerformed
                this.dispose();
                Game_screen juego = new Game_screen();
                juego.setLocationRelativeTo(null);
                juego.setTitle("Diner Dash");
                juego.setVisible(true);
    }//GEN-LAST:event_play_btnActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
                this.dispose();
                about_dev juego = new about_dev();
                juego.setLocationRelativeTo(null);
                juego.setTitle("Acerca del juego y desarrolladores");
                juego.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton ext_btn;
    private javax.swing.JLabel main_m_bckgrnd;
    private javax.swing.JButton play_btn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
